### PR TITLE
feat: Add date selection for balance/income

### PR DESCRIPTION
**Pull request by LarsV123**
Adds the option to choose dates for both income statements and balance statements.
For balance statements this means seeing the actual balance on a given date, while for income statements it means seeing the change in balance between two dates.

Also does some minor refactoring and regenerates translation files (due to new strings added).

### CODE REVIEW

**Comment by aaarunan** [comment]
I noticed that submitting the form on the income statement view sent a CSRF token as a GET parameter. Since this is a GET request, no CSRF token is needed.  CSRF tokens should not be sent as parameters either.

Otherwise, the rest of the PR looks good. However, I have some improvements I want to point out.

1. Split your work into different commits.
This makes it easier for me as a reviewer to see what you have done. 

2. Look into manager classes.
Each Django ORM has a manager class that is responsible for interacting with the database. It is essentially a query builder. Overriding the default manager class of an object could make your code more flexible, and is a nice asset to have as a Django developer

**Comment by LarsV123** [comment]
> I noticed that submitting the form on the income statement view sent a CSRF token as a GET parameter. Since this is a GET request, no CSRF token is needed. CSRF tokens should not be sent as parameters either.

Thanks, fixed!

> 
> Otherwise, the rest of the PR looks good. However, I have some improvements I want to point out.
> 
> 1. Split your work into different commits.
>    This makes it easier for me as a reviewer to see what you have done.

I normally try, but in this case it was hard to split in a way which made sense, as all the changes were tied together. I'll keep it in mind though.

> 2. Look into manager classes.
>    Each Django ORM has a manager class that is responsible for interacting with the database. It is essentially a query builder. Overriding the default manager class of an object could make your code more flexible, and is a nice asset to have as a Django developer

I looked at them briefly, but couldn't find a simple way to make it to what I wanted. I'll look into it more for future  work. Specific suggestions for this PR are welcome!

**Comment by LarsV123** [comment]
Quick note: When merging PRs on Github you can choose to "rebase and merge" from the dropdown, which avoids merge commits. That makes the history less messy.

image

**Comment by LarsV123** [comment]
I found a better way to write the query, so I'll refactor it to use a custom manager.

**Comment by aaarunan** [comment]
@LarsV123 This PR had to be reverted due to performance issues.

**Comment by aaarunan** [comment]
It looks like the query responsible for finding historical balance  the culprit [(with_historical_balance).](https://github.com/itkinside/ufs/blob/35ccee466340bfd2f25c2256d0294e9489acd8b4/itkufs/accounting/models.py#L231) 

The query itself is quite complex, with multiple aggregations and annotations. Each aggregation (annotation) requires a separate SQL query to be executed, so the more aggregations there are, the longer the query will take to run. Additionally, the use of Case and When statements can add extra processing overhead.

The production database has around 100 000 transaction entries. The app ends up hanging up and postgres spikes to 100%.  The query should be tested and optimized for transaction entries larger than 100 000.

**Comment by LarsV123** [comment]
> It looks like the query responsible for finding historical balance the culprit [(with_historical_balance).](https://github.com/itkinside/ufs/blob/35ccee466340bfd2f25c2256d0294e9489acd8b4/itkufs/accounting/models.py#L231)
> 
> The query itself is quite complex, with multiple aggregations and annotations. Each aggregation (annotation) requires a separate SQL query to be executed, so the more aggregations there are, the longer the query will take to run. Additionally, the use of Case and When statements can add extra processing overhead.
> 
> The production database has around 100 000 transaction entries. The app ends up hanging up and postgres spikes to 100%. The query should be tested and optimized for transaction entries larger than 100 000.

I see, I'll look into it. Do you happen to have sample data set I can use for testing?

**Pull request merged**
