### PR TITLE
feat: Add CSV export form

### LINKED ISSUE #107: Feature request: Export transactions to .CSV file
It would be useful to be able to export all transactions in a specified range to a .CSV file and download them.

- It should be possible to specify a date range (inclusive), such as 2022-01-01 to 2022-12-31.
- The exported data should include both user accounts and group accounts.
- Relevant columns include user/account ID, user/account name, transaction ID, credit amount, debit amount and transaction date (in YYYY-MM-DD format).
- This feature should perhaps be restricted to administrators.

### PR DESCRIPTION
**Pull request by LarsV123**
Adds a form allowing administrators to export transaction entries for a given time range to a CSV file.
This probably needs a bit more attention and polish, I'm not any good at Django.

Resolves #107

### CODE REVIEW

**Comment by LarsV123** [comment]
This needs more tests apparently, but adding them is non-trivial as there aren't any view tests to copy. Any suggestions?

**Comment by Kaholaz** [comment]
> This needs more tests apparently, but adding them is non-trivial as I can't find view tests to copy. Any suggestions?

What do you wish to create tests for?

**Comment by LarsV123** [comment]
> > This needs more tests apparently, but adding them is non-trivial as I can't find view tests to copy. Any suggestions?
> 
> What do you wish to create tests for?

I don't, but your pipeline is angry and complaining. Feel free to merge it ;-)

**Comment by Kaholaz** [comment]
I don't fully understand how it is implemented, so please correct me if I am wrong, but is an export-transactions not in any way admin protected? Other functionality that requires special privileges are marked red. This is not the case for `export transactions`.

If this is the case, one could use this functionality to see other people's previous transactions. This would extend the privileges of an unprivileged user.

This is not a major issue, but it is an issue that should be addressed, either by changing the link color (if the action requires admin privileges), or by making this action require admin privileges.

**Comment by LarsV123** [comment]
> I don't fully understand how it is implemented, so please correct me if I am wrong, but is an export-transactions not in any way admin protected? Other functionality that requires special privileges are marked red. This is not the case for `export transactions`.
> 
> If this is the case, one could use this functionality to see other people's previous transactions. This would extend the privileges of an unprivileged user.
> 
> This is not a major issue, but it is an issue that should be addressed, either by changing the link color (if the action requires admin privileges), or by making this action require admin privileges.

This was just a styling issue, fixed it now. The page was restricted to admins only already (see line 23 in `itkufs/common/views/display.py`)

**Comment by Kaholaz** [comment]
Alright! Looks good :)

**Pull request merged**
